# Generated by Django 5.1.5 on 2025-03-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_question_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Questions'},
        ),
    ]
