# Generated by Django 5.1.5 on 2025-03-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_assignment_options_alter_record_email_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
